# [package]
# name = "bot"
# version = "0.1.0"
# edition = "2024"
[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
incremental = true
codegen-units = 256

[profile.release]
opt-level = 3
codegen-units = 1
strip = true
panic = "abort"
lto = "fat"
debug = true
incremental = false

[workspace]
members = ["main", "utils", "framework", "macros"]
default-members = ["main"]
resolver = "2"

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
regex = "1.12"
colored = { version = "3" }
dashmap = "6.1.0"
moka = { version = "0.12", features = ["future"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_with = { version = "3.16" }
rayon = { version = "1" }

[workspace.dependencies.tokio]
version = "1"
features = ['macros', 'sync', 'time', 'rt-multi-thread']
default-features = false

[workspace.dependencies.serenity]
version = "0.12.4"
default-features = false
features = [
    'rustls_backend',
    "chrono",
    "builder",
    "client",
    "gateway",
    "http",
    "model",
    "utils",
    "voice",
]
