[package]
name = "main"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "matchawave"
path = "src/main.rs"

[build-dependencies]
dotenv = "0.15"

[dependencies]
serenity = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
dashmap = { workspace = true }
colored = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
fastrand = "2.3"

tokio = { workspace = true }
tokio-tungstenite = { version = "0.27", default-features = false, features = [
    'rustls',
    'connect',
] }
reqwest = { version = "0.13", features = ["json", "rustls"] }
rayon = { workspace = true }

utils = { path = "../utils" }
framework = { path = "../framework" }
moka = { workspace = true }
