use serenity::all::Event;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum DiscordEvent {
    CommandPermissionsUpdate,
    AutoModRuleCreate,
    AutoModRuleUpdate,
    AutoModRuleDelete,
    AutoModActionExecution,
    ChannelCreate,
    ChannelDelete,
    ChannelPinsUpdate,
    ChannelUpdate,
    GuildAuditLogEntryCreate,
    GuildBanAdd,
    GuildBanRemove,
    GuildCreate,
    GuildDelete,
    GuildEmojisUpdate,
    GuildIntegrationsUpdate,
    GuildMemberAdd,
    GuildMemberRemove,
    GuildMemberUpdate,
    GuildMembersChunk,
    GuildRoleCreate,
    GuildRoleDelete,
    GuildRoleUpdate,
    GuildStickersUpdate,
    GuildUpdate,
    InviteCreate,
    InviteDelete,
    MessageCreate,
    MessageDelete,
    MessageDeleteBulk,
    MessageUpdate,
    PresenceUpdate,
    ReactionAdd,
    ReactionRemove,
    ReactionRemoveAll,
    ReactionRemoveEmoji,
    Ready,
    Resumed,
    TypingStart,
    UserUpdate,
    VoiceStateUpdate,
    VoiceServerUpdate,
    VoiceChannelStatusUpdate,
    WebhookUpdate,
    InteractionCreate,
    IntegrationCreate,
    IntegrationUpdate,
    IntegrationDelete,
    StageInstanceCreate,
    StageInstanceUpdate,
    StageInstanceDelete,
    ThreadCreate,
    ThreadUpdate,
    ThreadDelete,
    ThreadListSync,
    ThreadMemberUpdate,
    ThreadMembersUpdate,
    GuildScheduledEventCreate,
    GuildScheduledEventUpdate,
    GuildScheduledEventDelete,
    GuildScheduledEventUserAdd,
    GuildScheduledEventUserRemove,
    EntitlementCreate,
    EntitlementUpdate,
    EntitlementDelete,
    MessagePollVoteAdd,
    MessagePollVoteRemove,
    Unknown,
}

impl From<&Event> for DiscordEvent {
    fn from(event: &Event) -> Self {
        match event {
            Event::CommandPermissionsUpdate(_) => DiscordEvent::CommandPermissionsUpdate,
            Event::AutoModRuleCreate(_) => DiscordEvent::AutoModRuleCreate,
            Event::AutoModRuleUpdate(_) => DiscordEvent::AutoModRuleUpdate,
            Event::AutoModRuleDelete(_) => DiscordEvent::AutoModRuleDelete,
            Event::AutoModActionExecution(_) => DiscordEvent::AutoModActionExecution,
            Event::ChannelCreate(_) => DiscordEvent::ChannelCreate,
            Event::ChannelDelete(_) => DiscordEvent::ChannelDelete,
            Event::ChannelPinsUpdate(_) => DiscordEvent::ChannelPinsUpdate,
            Event::GuildAuditLogEntryCreate(_) => DiscordEvent::GuildAuditLogEntryCreate,
            Event::GuildBanAdd(_) => DiscordEvent::GuildBanAdd,
            Event::GuildBanRemove(_) => DiscordEvent::GuildBanRemove,
            Event::GuildCreate(_) => DiscordEvent::GuildCreate,
            Event::GuildDelete(_) => DiscordEvent::GuildDelete,
            Event::GuildEmojisUpdate(_) => DiscordEvent::GuildEmojisUpdate,
            Event::GuildIntegrationsUpdate(_) => DiscordEvent::GuildIntegrationsUpdate,
            Event::GuildMemberAdd(_) => DiscordEvent::GuildMemberAdd,
            Event::GuildMemberRemove(_) => DiscordEvent::GuildMemberRemove,
            Event::GuildMemberUpdate(_) => DiscordEvent::GuildMemberUpdate,
            Event::GuildMembersChunk(_) => DiscordEvent::GuildMembersChunk,
            Event::GuildRoleCreate(_) => DiscordEvent::GuildRoleCreate,
            Event::GuildRoleDelete(_) => DiscordEvent::GuildRoleDelete,
            Event::GuildRoleUpdate(_) => DiscordEvent::GuildRoleUpdate,
            Event::GuildStickersUpdate(_) => DiscordEvent::GuildStickersUpdate,
            Event::GuildUpdate(_) => DiscordEvent::GuildUpdate,
            Event::InviteCreate(_) => DiscordEvent::InviteCreate,
            Event::InviteDelete(_) => DiscordEvent::InviteDelete,
            Event::MessageCreate(_) => DiscordEvent::MessageCreate,
            Event::MessageDelete(_) => DiscordEvent::MessageDelete,
            Event::MessageDeleteBulk(_) => DiscordEvent::MessageDeleteBulk,
            Event::MessageUpdate(_) => DiscordEvent::MessageUpdate,
            Event::PresenceUpdate(_) => DiscordEvent::PresenceUpdate,
            Event::ReactionAdd(_) => DiscordEvent::ReactionAdd,
            Event::ReactionRemove(_) => DiscordEvent::ReactionRemove,
            Event::ReactionRemoveAll(_) => DiscordEvent::ReactionRemoveAll,
            Event::ReactionRemoveEmoji(_) => DiscordEvent::ReactionRemoveEmoji,
            Event::Ready(_) => DiscordEvent::Ready,
            Event::Resumed(_) => DiscordEvent::Resumed,
            Event::TypingStart(_) => DiscordEvent::TypingStart,
            Event::UserUpdate(_) => DiscordEvent::UserUpdate,
            Event::VoiceStateUpdate(_) => DiscordEvent::VoiceStateUpdate,
            Event::VoiceServerUpdate(_) => DiscordEvent::VoiceServerUpdate,
            Event::VoiceChannelStatusUpdate(_) => DiscordEvent::VoiceChannelStatusUpdate,
            Event::WebhookUpdate(_) => DiscordEvent::WebhookUpdate,
            Event::InteractionCreate(_) => DiscordEvent::InteractionCreate,
            Event::IntegrationCreate(_) => DiscordEvent::IntegrationCreate,
            Event::IntegrationUpdate(_) => DiscordEvent::IntegrationUpdate,
            Event::IntegrationDelete(_) => DiscordEvent::IntegrationDelete,
            Event::StageInstanceCreate(_) => DiscordEvent::StageInstanceCreate,
            Event::StageInstanceUpdate(_) => DiscordEvent::StageInstanceUpdate,
            Event::StageInstanceDelete(_) => DiscordEvent::StageInstanceDelete,
            Event::ThreadCreate(_) => DiscordEvent::ThreadCreate,
            Event::ThreadUpdate(_) => DiscordEvent::ThreadUpdate,
            Event::ThreadDelete(_) => DiscordEvent::ThreadDelete,
            Event::ThreadListSync(_) => DiscordEvent::ThreadListSync,
            Event::ThreadMemberUpdate(_) => DiscordEvent::ThreadMemberUpdate,
            Event::ThreadMembersUpdate(_) => DiscordEvent::ThreadMembersUpdate,
            Event::GuildScheduledEventCreate(_) => DiscordEvent::GuildScheduledEventCreate,
            Event::GuildScheduledEventUpdate(_) => DiscordEvent::GuildScheduledEventUpdate,
            Event::GuildScheduledEventDelete(_) => DiscordEvent::GuildScheduledEventDelete,
            Event::GuildScheduledEventUserAdd(_) => DiscordEvent::GuildScheduledEventUserAdd,
            Event::GuildScheduledEventUserRemove(_) => DiscordEvent::GuildScheduledEventUserRemove,
            Event::EntitlementCreate(_) => DiscordEvent::EntitlementCreate,
            Event::EntitlementUpdate(_) => DiscordEvent::EntitlementUpdate,
            Event::EntitlementDelete(_) => DiscordEvent::EntitlementDelete,
            Event::MessagePollVoteAdd(_) => DiscordEvent::MessagePollVoteAdd,
            Event::MessagePollVoteRemove(_) => DiscordEvent::MessagePollVoteRemove,
            _ => DiscordEvent::Unknown,
        }
    }
}
